version: '2'

services:
  # web with xdebug - dropteam images
  web:
    # dropteam/drupal-php available tags: 5.6-apache, 7.0-apache
    image: dropteam/drupal-php:7.0-apache

    ports:
      - "${PORT_WEB}:80"
      - "${PORT_WEBXDEBUG}:9000"
    environment:
      - SERVERNAME=${XDEBUG_SERVERNAME}
      - SERVERALIAS=${XDEBUG_SERVERALIAS}
      - DOCUMENTROOT=${DOCUMENTROOT}
    volumes:
      - ${LOCALPATH}:/var/www/html/:cached
    depends_on:
      - database
      - memcache
    links:
      - database:mysql
      - memcache
    tty: true
    env_file: .env

  # database container - dropteam images
  database:
    image: mysql:5.7
    ports:
      - "${PORT_DATABASE}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_CONFIG}:/etc/mysql/conf.d/

  # phpmyadmin container - dropteam images
  phpmyadmin:
    image: dropteam/docker-phpmyadmin
    ports:
      - "${PORT_PHPMYADMIN}:80"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - UPLOAD_SIZE=${UPLOAD_SIZE}
    depends_on:
      - database
    links:
      - database:mysql

  # memcache container - official images
  memcache:
    image: memcached
    ports:
      - "${PORT_MEMCACHE}:11211"
    command: memcached -m ${MEMCACHE_MEM}
